# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: |
          options(crayon.enabled = TRUE)
          rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
        
      - name: Install pacman
        run: Rscript -e 'install.packages(c("pacman","remotes", "extrafont"))'
        
      - name: Install theme
        run: Rscript -e 'remotes::install_github("yukatapangolin/themeglyptodon")'
        
      - name: Copy fonts
        run: Rscript -e 'dir=system.file("fonts", "goldman-sans", package="glyptodon");system("mkdir -p ~/Library/Fonts");system(paste0("cp ", dir, "/*.ttf", " ~/Library/Fonts"))'

      - name: Copy fonts
        run: Rscript -e 'dir=system.file("fonts", "roboto", package="glyptodon");system("mkdir -p ~/Library/Fonts");system(paste0("cp ", dir, "/*.ttf", " ~/Library/Fonts"))'

      - name: Copy fonts
        run: Rscript -e 'dir=system.file("fonts", "roboto-condensed", package="glyptodon");system("mkdir -p ~/Library/Fonts");system(paste0("cp ", dir, "/*.ttf", " ~/Library/Fonts"))'
      - name: Copy fonts
      
        run: Rscript -e 'dir=system.file("fonts", "pt-sans", package="glyptodon");system("mkdir -p ~/Library/Fonts");system(paste0("cp ", dir, "/*.ttf", " ~/Library/Fonts"))'
        
      - name: Copy fonts
        run: Rscript -e 'dir=system.file("fonts", "ibm-plex-sans", package="glyptodon");system("mkdir -p ~/Library/Fonts");system(paste0("cp ", dir, "/*.ttf", " ~/Library/Fonts"))'
        
      - name: Copy fonts
        run: Rscript -e 'dir=system.file("fonts", "source-sans-pro", package="glyptodon");system("mkdir -p ~/Library/Fonts");system(paste0("cp ", dir, "/*.ttf", " ~/Library/Fonts"))'
               
      - name: Install fonts
        run: Rscript -e 'extrafont::font_import(prompt = FALSE); extrafont::font_import(paths = system.file("fonts", "goldman-sans", package="glyptodon"), prompt = FALSE); extrafont::font_import(paths = system.file("fonts", "roboto", package="glyptodon"), prompt = FALSE); extrafont::font_import(paths = system.file("fonts", "roboto-condensed", package="glyptodon"), prompt = FALSE); extrafont::font_import(paths = system.file("fonts", "ibm-plex-sans", package="glyptodon"), prompt = FALSE); extrafont::font_import(paths = system.file("fonts", "source-sans-pro", package="glyptodon"), prompt = FALSE)'  
